In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv(
    "../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

In [3]:
df.shape

(7043, 21)

In [4]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [5]:
df["Churn"] = df["Churn"].map({
    "No": 0,
    "Yes": 1
})

In [6]:
df = df.drop("customerID", axis=1)

In [7]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [8]:
print("X:", X.shape)
print("y:", y.shape)

X: (7043, 19)
y: (7043,)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
print("Original:")
print(y.value_counts(normalize=True))

print("\nTrain:")
print(y_train.value_counts(normalize=True))

print("\nTest:")
print(y_test.value_counts(normalize=True))

Original:
Churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

Train:
Churn
0    0.734647
1    0.265353
Name: proportion, dtype: float64

Test:
Churn
0    0.734564
1    0.265436
Name: proportion, dtype: float64

In [12]:
categorical_features = X_train.select_dtypes(
    include=["object", "str"]
).columns.tolist()

numerical_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

In [13]:
print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [15]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        )
    ]
)

In [16]:
logistic_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(
            max_iter=1000,
            random_state=42
        ))
    ]
)

In [17]:
logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [18]:
y_pred = logistic_pipeline.predict(X_test)

In [19]:
y_prob = logistic_pipeline.predict_proba(X_test)[:, 1]

In [20]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [21]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.8055358410220014
Precision: 0.6572327044025157
Recall   : 0.5588235294117647
F1 Score : 0.6040462427745664
ROC-AUC  : 0.8421349040274871

In [22]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [23]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[926 109]
 [165 209]]

In [24]:
results = []

results.append({
    "Model": "Logistic Regression",
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
})

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135

In [25]:
from sklearn.svm import SVC

In [26]:
svm_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", SVC(
            kernel="rbf",
            C=1.0,
            probability=True,
            random_state=42
        ))
    ]
)

In [27]:
svm_pipeline.fit(X_train, y_train)

c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', SVC(probability=True, random_state=42))])

In [28]:
svm_pred = svm_pipeline.predict(X_test)

svm_prob = svm_pipeline.predict_proba(X_test)[:, 1]

In [29]:
svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
svm_roc_auc = roc_auc_score(y_test, svm_prob)

print("SVM Results")
print("----------------------")
print("Accuracy :", svm_accuracy)
print("Precision:", svm_precision)
print("Recall   :", svm_recall)
print("F1 Score :", svm_f1)
print("ROC-AUC  :", svm_roc_auc)

SVM Results
----------------------
Accuracy : 0.7913413768630234
Precision: 0.6418439716312057
Recall   : 0.4839572192513369
F1 Score : 0.551829268292683
ROC-AUC  : 0.7901754114030328

In [30]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1035
           1       0.64      0.48      0.55       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [31]:
print(confusion_matrix(y_test, svm_pred))

[[934 101]
 [193 181]]

In [32]:
results.append({
    "Model": "SVM",
    "Accuracy": svm_accuracy,
    "Precision": svm_precision,
    "Recall": svm_recall,
    "F1": svm_f1,
    "ROC-AUC": svm_roc_auc
})

In [33]:
results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135
1                  SVM  0.791341   0.641844  0.483957  0.551829  0.790175

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", KNeighborsClassifier(n_neighbors=5))
    ]
)

In [36]:
knn_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', KNeighborsClassifier())])

In [37]:
knn_pred = knn_pipeline.predict(X_test)

knn_prob = knn_pipeline.predict_proba(X_test)[:, 1]

In [38]:
knn_accuracy = accuracy_score(y_test, knn_pred)
knn_precision = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)
knn_roc_auc = roc_auc_score(y_test, knn_prob)

print("KNN Results")
print("----------------------")
print("Accuracy :", knn_accuracy)
print("Precision:", knn_precision)
print("Recall   :", knn_recall)
print("F1 Score :", knn_f1)
print("ROC-AUC  :", knn_roc_auc)

KNN Results
----------------------
Accuracy : 0.7636621717530163
Precision: 0.5526992287917738
Recall   : 0.5748663101604278
F1 Score : 0.563564875491481
ROC-AUC  : 0.7896096515022346

In [39]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84      1035
           1       0.55      0.57      0.56       374

    accuracy                           0.76      1409
   macro avg       0.70      0.70      0.70      1409
weighted avg       0.77      0.76      0.77      1409

In [40]:
print(confusion_matrix(y_test, knn_pred))

[[861 174]
 [159 215]]

In [41]:
results.append({
    "Model": "KNN",
    "Accuracy": knn_accuracy,
    "Precision": knn_precision,
    "Recall": knn_recall,
    "F1": knn_f1,
    "ROC-AUC": knn_roc_auc
})

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135
1                  SVM  0.791341   0.641844  0.483957  0.551829  0.790175
2                  KNN  0.763662   0.552699  0.574866  0.563565  0.789610

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
decision_tree_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", DecisionTreeClassifier(random_state=42))
    ]
)

In [44]:
decision_tree_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [45]:
dt_pred = decision_tree_pipeline.predict(X_test)

dt_prob = decision_tree_pipeline.predict_proba(X_test)[:, 1]

In [46]:
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_precision = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)
dt_roc_auc = roc_auc_score(y_test, dt_prob)

print("Decision Tree Results")
print("----------------------")
print("Accuracy :", dt_accuracy)
print("Precision:", dt_precision)
print("Recall   :", dt_recall)
print("F1 Score :", dt_f1)
print("ROC-AUC  :", dt_roc_auc)

Decision Tree Results
----------------------
Accuracy : 0.7210787792760823
Precision: 0.4754521963824289
Recall   : 0.4919786096256685
F1 Score : 0.4835742444152431
ROC-AUC  : 0.6476762510010592

In [47]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.81      0.80      0.81      1035
           1       0.48      0.49      0.48       374

    accuracy                           0.72      1409
   macro avg       0.64      0.65      0.65      1409
weighted avg       0.72      0.72      0.72      1409

In [48]:
print(confusion_matrix(y_test, dt_pred))

[[832 203]
 [190 184]]

In [49]:
results.append({
    "Model": "Decision Tree",
    "Accuracy": dt_accuracy,
    "Precision": dt_precision,
    "Recall": dt_recall,
    "F1": dt_f1,
    "ROC-AUC": dt_roc_auc
})

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135
1                  SVM  0.791341   0.641844  0.483957  0.551829  0.790175
2                  KNN  0.763662   0.552699  0.574866  0.563565  0.789610
3        Decision Tree  0.721079   0.475452  0.491979  0.483574  0.647676

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
random_forest_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(
            n_estimators=100,
            random_state=42
        ))
    ]
)

In [52]:
random_forest_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [53]:
rf_pred = random_forest_pipeline.predict(X_test)

rf_prob = random_forest_pipeline.predict_proba(X_test)[:, 1]

In [54]:
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_roc_auc = roc_auc_score(y_test, rf_prob)

print("Random Forest Results")
print("----------------------")
print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)
print("ROC-AUC  :", rf_roc_auc)

Random Forest Results
----------------------
Accuracy : 0.7863733144073811
Precision: 0.6254295532646048
Recall   : 0.48663101604278075
F1 Score : 0.5473684210526316
ROC-AUC  : 0.8185099072567104

In [55]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.63      0.49      0.55       374

    accuracy                           0.79      1409
   macro avg       0.73      0.69      0.70      1409
weighted avg       0.77      0.79      0.78      1409

In [56]:
print(confusion_matrix(y_test, rf_pred))

[[926 109]
 [192 182]]

In [57]:
results.append({
    "Model": "Random Forest",
    "Accuracy": rf_accuracy,
    "Precision": rf_precision,
    "Recall": rf_recall,
    "F1": rf_f1,
    "ROC-AUC": rf_roc_auc
})

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135
1                  SVM  0.791341   0.641844  0.483957  0.551829  0.790175
2                  KNN  0.763662   0.552699  0.574866  0.563565  0.789610
3        Decision Tree  0.721079   0.475452  0.491979  0.483574  0.647676
4        Random Forest  0.786373   0.625430  0.486631  0.547368  0.818510

In [58]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
gradient_boosting_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", GradientBoostingClassifier(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=3,
            random_state=42
        ))
    ]
)

In [60]:
gradient_boosting_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [61]:
gb_pred = gradient_boosting_pipeline.predict(X_test)

gb_prob = gradient_boosting_pipeline.predict_proba(X_test)[:, 1]

In [62]:
gb_accuracy = accuracy_score(y_test, gb_pred)
gb_precision = precision_score(y_test, gb_pred)
gb_recall = recall_score(y_test, gb_pred)
gb_f1 = f1_score(y_test, gb_pred)
gb_roc_auc = roc_auc_score(y_test, gb_prob)

print("Gradient Boosting Results")
print("----------------------")
print("Accuracy :", gb_accuracy)
print("Precision:", gb_precision)
print("Recall   :", gb_recall)
print("F1 Score :", gb_f1)
print("ROC-AUC  :", gb_roc_auc)

Gradient Boosting Results
----------------------
Accuracy : 0.8026969481902059
Precision: 0.6655172413793103
Recall   : 0.516042780748663
F1 Score : 0.5813253012048193
ROC-AUC  : 0.8432754656539823

In [63]:
print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1035
           1       0.67      0.52      0.58       374

    accuracy                           0.80      1409
   macro avg       0.75      0.71      0.73      1409
weighted avg       0.79      0.80      0.79      1409

In [64]:
print(confusion_matrix(y_test, gb_pred))

[[938  97]
 [181 193]]

In [65]:
results.append({
    "Model": "Gradient Boosting",
    "Accuracy": gb_accuracy,
    "Precision": gb_precision,
    "Recall": gb_recall,
    "F1": gb_f1,
    "ROC-AUC": gb_roc_auc
})

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.842135
1                  SVM  0.791341   0.641844  0.483957  0.551829  0.790175
2                  KNN  0.763662   0.552699  0.574866  0.563565  0.789610
3        Decision Tree  0.721079   0.475452  0.491979  0.483574  0.647676
4        Random Forest  0.786373   0.625430  0.486631  0.547368  0.818510
5    Gradient Boosting  0.802697   0.665517  0.516043  0.581325  0.843275

## Cross-Validation

In [66]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [67]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [68]:
logistic_cv_scores = cross_val_score(
    logistic_pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring="roc_auc"
)

In [69]:
print("Logistic Regression CV ROC-AUC scores:")
print(logistic_cv_scores)

Logistic Regression CV ROC-AUC scores:
[0.84791899 0.82518015 0.84191669 0.86296714 0.85302075]

In [70]:
print("Mean ROC-AUC:", logistic_cv_scores.mean())
print("Std ROC-AUC :", logistic_cv_scores.std())

Mean ROC-AUC: 0.8462007441910661
Std ROC-AUC : 0.012576130140361557

In [71]:
models = {
    "Logistic Regression": logistic_pipeline,
    "SVM": svm_pipeline,
    "KNN": knn_pipeline,
    "Decision Tree": decision_tree_pipeline,
    "Random Forest": random_forest_pipeline,
    "Gradient Boosting": gradient_boosting_pipeline
}

In [72]:
cv_results = []

for model_name, model in models.items():

    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc"
    )

    cv_results.append({
        "Model": model_name,
        "Mean ROC-AUC": scores.mean(),
        "Std ROC-AUC": scores.std()
    })

c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
c:\Users\bikes\OneDrive\Desktop\Frontend lo\python\customer-churn-ml\.venv\Lib\site-packages\sklearn\svm\_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

In [73]:
cv_results_df = pd.DataFrame(cv_results)

cv_results_df.sort_values(
    by="Mean ROC-AUC",
    ascending=False
)

                 Model  Mean ROC-AUC  Std ROC-AUC
5    Gradient Boosting      0.848105     0.012637
0  Logistic Regression      0.846201     0.012576
4        Random Forest      0.817815     0.012279
1                  SVM      0.799827     0.015761
2                  KNN      0.782611     0.006751
3        Decision Tree      0.653354     0.010606

## Gradient Boosting Hyperparameter Tuning

In [74]:
from sklearn.model_selection import GridSearchCV

In [75]:
gb_param_grid = {
    "model__n_estimators": [100, 200],
    "model__learning_rate": [0.05, 0.1],
    "model__max_depth": [2, 3],
    "model__min_samples_split": [2, 5],
    "model__min_samples_leaf": [1, 2]
}

In [76]:
gb_grid_search = GridSearchCV(
    estimator=gradient_boosting_pipeline,
    param_grid=gb_param_grid,
    cv=cv,
    scoring="roc_auc",
    n_jobs=-1,
    verbose=1
)

In [77]:
gb_grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['SeniorCitizen',
                                                                          'tenure',
                                                                          'MonthlyCharges',
                                                                          'TotalCharges']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'Internet...
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod'])])),
                                       ('model',
                                        GradientBoostingClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [2, 3],
                         'model__min_samples_leaf': [1, 2],
                         'model__min_samples_split': [2, 5],
                         'model__n_estimators': [100, 200]},
             scoring='roc_auc', verbose=1)

In [78]:
print("Best Parameters:")
print(gb_grid_search.best_params_)

Best Parameters:
{'model__learning_rate': 0.05, 'model__max_depth': 2, 'model__min_samples_leaf': 2, 'model__min_samples_split': 2, 'model__n_estimators': 200}

In [79]:
print("Best CV ROC-AUC:")
print(gb_grid_search.best_score_)

Best CV ROC-AUC:
0.8498409017544046

In [80]:
best_gb_model = gb_grid_search.best_estimator_

In [81]:
gb_baseline_cv = 0.848105
gb_tuned_cv = gb_grid_search.best_score_

print("Gradient Boosting CV Comparison")
print("--------------------------------")
print("Baseline CV ROC-AUC:", gb_baseline_cv)
print("Tuned CV ROC-AUC   :", gb_tuned_cv)
print("Improvement        :", gb_tuned_cv - gb_baseline_cv)

Gradient Boosting CV Comparison
--------------------------------
Baseline CV ROC-AUC: 0.848105
Tuned CV ROC-AUC   : 0.8498409017544046
Improvement        : 0.001735901754404634

## Logistic Regression Hyperparameter Tuning

In [82]:
lr_param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100]
}

In [83]:
lr_grid_search = GridSearchCV(
    estimator=logistic_pipeline,
    param_grid=lr_param_grid,
    cv=cv,
    scoring="roc_auc",
    n_jobs=-1,
    verbose=1
)

In [84]:
lr_grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['SeniorCitizen',
                                                                          'tenure',
                                                                          'MonthlyCharges',
                                                                          'TotalCharges']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'InternetService',
                                                                          'OnlineSecurity',
                                                                          'OnlineBackup',
                                                                          'DeviceProtection',
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod'])])),
                                       ('model',
                                        LogisticRegression(max_iter=1000,
                                                           random_state=42))]),
             n_jobs=-1, param_grid={'model__C': [0.01, 0.1, 1, 10, 100]},
             scoring='roc_auc', verbose=1)

In [85]:
print("Best Parameters:")
print(lr_grid_search.best_params_)

Best Parameters:
{'model__C': 10}

In [86]:
print("Best CV ROC-AUC:")
print(lr_grid_search.best_score_)

Best CV ROC-AUC:
0.8463914680855682

In [87]:
best_lr_model = lr_grid_search.best_estimator_

In [88]:
lr_baseline_cv = 0.846201
lr_tuned_cv = lr_grid_search.best_score_

print("Logistic Regression CV Comparison")
print("--------------------------------")
print("Baseline CV ROC-AUC:", lr_baseline_cv)
print("Tuned CV ROC-AUC   :", lr_tuned_cv)
print("Improvement        :", lr_tuned_cv - lr_baseline_cv)

Logistic Regression CV Comparison
--------------------------------
Baseline CV ROC-AUC: 0.846201
Tuned CV ROC-AUC   : 0.8463914680855682
Improvement        : 0.00019046808556821837

In [89]:
rf_param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [None, 10],
    "model__min_samples_leaf": [1, 2],
    "model__max_features": ["sqrt", "log2"]
}

In [90]:
rf_grid_search = GridSearchCV(
    estimator=random_forest_pipeline,
    param_grid=rf_param_grid,
    cv=cv,
    scoring="roc_auc",
    n_jobs=-1,
    verbose=1
)

rf_grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['SeniorCitizen',
                                                                          'tenure',
                                                                          'MonthlyCharges',
                                                                          'TotalCharges']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'Internet...
                                                                          'DeviceProtection',
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod'])])),
                                       ('model',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [None, 10],
                         'model__max_features': ['sqrt', 'log2'],
                         'model__min_samples_leaf': [1, 2],
                         'model__n_estimators': [100, 200]},
             scoring='roc_auc', verbose=1)

In [91]:
print("Best Parameters:")
print(rf_grid_search.best_params_)

print("\nBest CV ROC-AUC:")
print(rf_grid_search.best_score_)

Best Parameters:
{'model__max_depth': 10, 'model__max_features': 'log2', 'model__min_samples_leaf': 2, 'model__n_estimators': 200}

Best CV ROC-AUC:
0.845178465151984

In [92]:
rf_baseline_cv = 0.817815
rf_tuned_cv = rf_grid_search.best_score_

print("Random Forest CV Comparison")
print("--------------------------------")
print("Baseline CV ROC-AUC:", rf_baseline_cv)
print("Tuned CV ROC-AUC   :", rf_tuned_cv)
print("Improvement        :", rf_tuned_cv - rf_baseline_cv)

Random Forest CV Comparison
--------------------------------
Baseline CV ROC-AUC: 0.817815
Tuned CV ROC-AUC   : 0.845178465151984
Improvement        : 0.027363465151984068

In [93]:
tuned_model_results = pd.DataFrame({
    "Model": [
        "Gradient Boosting",
        "Logistic Regression",
        "Random Forest"
    ],
    "Baseline CV ROC-AUC": [
        0.848105,
        0.846201,
        0.817815
    ],
    "Tuned CV ROC-AUC": [
        gb_grid_search.best_score_,
        lr_grid_search.best_score_,
        rf_grid_search.best_score_
    ]
})

tuned_model_results["Improvement"] = (
    tuned_model_results["Tuned CV ROC-AUC"]
    - tuned_model_results["Baseline CV ROC-AUC"]
)

tuned_model_results

                 Model  Baseline CV ROC-AUC  Tuned CV ROC-AUC  Improvement
0    Gradient Boosting             0.848105          0.849841     0.001736
1  Logistic Regression             0.846201          0.846391     0.000190
2        Random Forest             0.817815          0.845178     0.027363

In [94]:
best_models = {
    "Gradient Boosting": gb_grid_search.best_estimator_,
    "Logistic Regression": lr_grid_search.best_estimator_,
    "Random Forest": rf_grid_search.best_estimator_
}

In [95]:
for name, model in best_models.items():
    print(name)
    print(model)
    print()

Gradient Boosting
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model',
                 GradientBoostingClassifier(learning_rate=0.05, max_depth=2,
                                            min_samples_leaf=2,
                                            n_estimators=200,
                                            random_state=42))])

Logistic Regression
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model',
                 LogisticRegression(C=10, max_iter=1000, random_state=42))])

Random Forest
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model',
                 RandomForestClassifier(max_depth=10, max_features='log2',
                                        min_samples_leaf=2, n_estimators=200,
                                        random_state=42))])